development:
  adapter: postgresql
  encoding: unicode
  database: rocko_development
  pool: 5
  username: sally
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: rocko_test
  pool: 5
  username: sally
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rocko_production
  pool: 5
  username: sally
  password:
